obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
footprint_padding: 0.1

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 1.0
transform_tolerance: 0.5

inflation_layer:
  inflation_radius: 1.0

cost_scaling_factor: 3.0

obstacle_layer:
  observation_sources: laser
  rpilidar_laser: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}
  
static:
  map_topic: map
  subscribe_to_updates: true