DWAPlannerROS:


  max_vel_x: 0.22 
  min_vel_x: -0.22

  max_vel_y: 0.0 
  min_vel_y: 0.0  

  max_vel_trans: 0.22
  min_vel_trans: 0.11 
  trans_stopped_vel: 0.05

  max_vel_theta: 2.75
  min_vel_theta: 1.37  
  theta_stopped_vel: 0.0

  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  acc_lim_y: 0     

  yaw_goal_tolerance: 0.17 
  xy_goal_tolerance: 0.05
  latch_xy_goal_tolerance: false  

  sim_time: 1.5       
  vx_samples: 20       
  vy_samples: 0       
  vtheta_samples: 40  

  path_distance_bias: 32.0     
  goal_distance_bias: 20.0     
  occdist_scale: 0.02            
  forward_point_distance: 0.325 
  stop_time_buffer: 0.2        
  scaling_speed: 0.25          
  max_scaling_factor: 0.2       

  oscillation_reset_dist: 0.05  

  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom

  holonomic_robot: false